// web/src/components/Dashboard.tsx
import React, { useEffect, useState, useCallback } from "react";
import {
  getGroup,
  getBalances,
  getSettlements,
  toggleSimplify,
  deleteExpense,
  deleteUser,
  settle,
} from "../services/api";
import * as Types from "../types";
import { useToast } from "../contexts/ToastContext";
import GroupHeader from "./GroupHeader";
import MemberList from "./MemberList";
import UserForm from "./UserForm";
import ExpenseList from "./ExpenseList";
import ExpenseForm from "./ExpenseForm";
import BalanceSummary from "./BalanceSummary";
import SettlementCard from "./SettlementCard";

interface DashboardProps {
  refreshKey: number;
  onRefresh: () => void;
  onUpdateGroup: (groupId: number, newName: string) => Promise<void>;
  onDeleteGroup: () => void;
}

const Dashboard: React.FC<DashboardProps> = ({
  refreshKey,
  onRefresh,
  onUpdateGroup,
  onDeleteGroup,
}) => {
  const toast = useToast();
  const [group, setGroup] = useState<Types.Group | null>(null);
  const [balances, setBalances] = useState<Record<string, number>>({});
  const [settlements, setSettlements] = useState<Types.Settlement[]>([]);
  const [error, setError] = useState<string | null>(null);

  const fetchGroupData = useCallback(async () => {
    setError(null);
    try {
      const [groupData, balancesData, settlementsData] = await Promise.all([
        getGroup(),
        getBalances(),
        getSettlements(),
      ]);
      setGroup(groupData);
      setBalances(balancesData.balances);
      setSettlements(settlementsData.settlements);
    } catch (err) {
      const errorMsg =
        err instanceof Error ? err.message : "Unknown error occurred";
      setError(errorMsg);
      toast.error(errorMsg);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const fetchGroupOnly = useCallback(async () => {
    try {
      const groupData = await getGroup();
      setGroup(groupData);
    } catch (err) {
      toast.error(
        err instanceof Error ? err.message : "Failed to refresh group",
      );
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    fetchGroupData();
  }, [refreshKey, fetchGroupData]);

  const handleToggleSimplify = useCallback(async () => {
    try {
      await toggleSimplify();
      onRefresh(); // Refresh to get updated settlements
    } catch (err) {
      toast.error(
        err instanceof Error ? err.message : "Failed to toggle simplify",
      );
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [onRefresh]);

  const handleDeleteExpense = async (
    expenseId: number,
    description: string,
  ) => {
    toast.confirm("Are you sure you want to delete this expense?", async () => {
      if (!group) return;

      const previousExpenses = [...group.expenses];
      setGroup({
        ...group,
        expenses: group.expenses.filter((e) => e.id !== expenseId),
      });

      try {
        await deleteExpense(expenseId);
        onRefresh();
        toast.success(`Expense "${description}" deleted successfully`);
      } catch (err) {
        setGroup({ ...group, expenses: previousExpenses });
        toast.error(
          err instanceof Error ? err.message : "Failed to delete expense",
        );
      }
    });
  };

  const handleDeleteUser = async (userId: number, userName: string) => {
    toast.confirm(
      `Are you sure you want to remove ${userName} from this group?`,
      async () => {
        if (!group) return;

        const previousMembers = [...group.members];
        setGroup({
          ...group,
          members: group.members.filter((m) => m.id !== userId),
        });

        try {
          await deleteUser(userId);
          onRefresh();
          toast.success(`${userName} removed from group successfully`);
        } catch (err) {
          setGroup({ ...group, members: previousMembers });
          toast.error(
            err instanceof Error ? err.message : "Failed to remove user",
          );
        }
      },
    );
  };

  const handleSettle = async (from: string, to: string, amount: number) => {
    toast.confirm(
      `Mark ${from} as having paid ${to} $${amount.toFixed(2)}?`,
      async () => {
        setSettlements((prev) =>
          prev.map((s) =>
            s.from === from && s.to === to ? { ...s, settled: true } : s,
          ),
        );

        try {
          await settle(from, to, amount);
          await fetchGroupOnly();
          toast.success(`Settlement recorded: ${from} paid ${to}`);
        } catch (err) {
          setSettlements((prev) =>
            prev.map((s) =>
              s.from === from && s.to === to ? { ...s, settled: false } : s,
            ),
          );
          toast.error(
            err instanceof Error ? err.message : "Failed to record settlement",
          );
        }
      },
    );
  };

  if (error) {
    return (
      <div className="alert alert-danger mt-3">Error loading data: {error}</div>
    );
  }

  if (!group) {
    return (
      <div className="loading-state">
        <div className="loading-spinner"></div>
        <p>Loading group data...</p>
      </div>
    );
  }

  return (
    <div className="dashboard">
      <div className="card dashboard-card">
        <GroupHeader
          groupName={group.name}
          groupId={group.id}
          onUpdateGroup={onUpdateGroup}
          onDeleteGroup={onDeleteGroup}
        />
      </div>

      <div className="dashboard-grid">
        <div className="dashboard-column">
          <MemberList members={group.members} onDeleteUser={handleDeleteUser} />
          <UserForm onUserAdded={onRefresh} />
        </div>

        <div className="dashboard-column dashboard-column-wide">
          <ExpenseList
            expenses={group.expenses}
            onDeleteExpense={handleDeleteExpense}
          />
          <ExpenseForm onExpenseAdded={onRefresh} refreshKey={refreshKey} />
        </div>

        <div className="dashboard-column">
          <BalanceSummary balances={balances} />
          <SettlementCard
            settlements={settlements}
            onSettle={handleSettle}
            isSimplified={group.simplify_debts}
            onToggleSimplify={handleToggleSimplify}
          />
        </div>
      </div>
    </div>
  );
};

export default Dashboard;

// web/src/lib/Dashboard.svelte
<script lang="ts">
  import {
    getGroup,
    getBalances,
    getSettlements,
    toggleSimplify,
    deleteExpense,
    deleteUser,
    settle,
  } from "./api";
  import type { Group, Expense, Settlement } from "./types";
  import { toast } from "./stores/toast";
  import GroupHeader from "./GroupHeader.svelte";
  import MemberList from "./MemberList.svelte";
  import UserForm from "./UserForm.svelte";
  import ExpenseList from "./ExpenseList.svelte";
  import ExpenseForm from "./ExpenseForm.svelte";
  import BalanceSummary from "./BalanceSummary.svelte";
  import SettlementCard from "./SettlementCard.svelte";

  interface Props {
    refreshKey: number;
    onRefresh: () => void;
    onUpdateGroup: (groupId: number, newName: string) => Promise<void>;
    onDeleteGroup: () => void;
  }

  let { refreshKey, onRefresh, onUpdateGroup, onDeleteGroup }: Props = $props();

  let group = $state<Group | null>(null);
  let balances = $state<Record<string, number>>({});
  let settlements = $state<Settlement[]>([]);
  let error = $state<string | null>(null);
  let editingExpense = $state<Expense | null>(null);

  async function fetchGroupData() {
    error = null;
    try {
      const [groupData, balancesData, settlementsData] = await Promise.all([
        getGroup(),
        getBalances(),
        getSettlements(),
      ]);
      group = groupData;
      balances = balancesData.balances;
      settlements = settlementsData.settlements;
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : "Unknown error occurred";
      error = errorMsg;
      toast.error(errorMsg);
    }
  }

  async function fetchGroupOnly() {
    try {
      const groupData = await getGroup();
      group = groupData;
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Failed to refresh group");
    }
  }

  async function handleToggleSimplify() {
    try {
      await toggleSimplify();
      onRefresh();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Failed to toggle simplify");
    }
  }

  function handleDeleteExpense(expenseId: number, description: string) {
    toast.confirm("Are you sure you want to delete this expense?", async () => {
      if (!group) return;

      const previousExpenses = [...group.expenses];
      group = {
        ...group,
        expenses: group.expenses.filter((e) => e.id !== expenseId),
      };

      try {
        await deleteExpense(expenseId);
        onRefresh();
        toast.success(`Expense "${description}" deleted successfully`);
      } catch (err) {
        group = { ...group!, expenses: previousExpenses };
        toast.error(err instanceof Error ? err.message : "Failed to delete expense");
      }
    });
  }

  function handleDeleteUser(userId: number, userName: string) {
    toast.confirm(
      `Are you sure you want to remove ${userName} from this group?`,
      async () => {
        if (!group) return;

        const previousMembers = [...group.members];
        group = {
          ...group,
          members: group.members.filter((m) => m.id !== userId),
        };

        try {
          await deleteUser(userId);
          onRefresh();
          toast.success(`${userName} removed from group successfully`);
        } catch (err) {
          group = { ...group!, members: previousMembers };
          toast.error(err instanceof Error ? err.message : "Failed to remove user");
        }
      }
    );
  }

  async function handleSettle(from: string, to: string, amount: number) {
    toast.confirm(
      `Mark ${from} as having paid ${to} $${amount.toFixed(2)}?`,
      async () => {
        settlements = settlements.map((s) =>
          s.from === from && s.to === to ? { ...s, settled: true } : s
        );

        try {
          await settle(from, to, amount);
          await fetchGroupOnly();
          toast.success(`Settlement recorded: ${from} paid ${to}`);
        } catch (err) {
          settlements = settlements.map((s) =>
            s.from === from && s.to === to ? { ...s, settled: false } : s
          );
          toast.error(err instanceof Error ? err.message : "Failed to record settlement");
        }
      }
    );
  }

  function handleEditExpense(expense: Expense) {
    editingExpense = expense;
  }

  function handleCancelEdit() {
    editingExpense = null;
  }

  // Fetch data on refreshKey change
  $effect(() => {
    refreshKey;
    fetchGroupData();
  });
</script>

{#if error}
  <div class="alert alert-danger mt-3">Error loading data: {error}</div>
{:else if !group}
  <div class="loading-state">
    <div class="loading-spinner"></div>
    <p>Loading group data...</p>
  </div>
{:else}
  <div class="dashboard">
    <div class="card dashboard-card">
      <GroupHeader
        groupName={group.name}
        groupId={group.id}
        {onUpdateGroup}
        {onDeleteGroup}
      />
    </div>

    <div class="dashboard-grid">
      <div class="dashboard-column">
        <MemberList members={group.members} onDeleteUser={handleDeleteUser} />
        <UserForm onUserAdded={onRefresh} />
      </div>

      <div class="dashboard-column dashboard-column-wide">
        <ExpenseList
          expenses={group.expenses}
          onDeleteExpense={handleDeleteExpense}
          onEditExpense={handleEditExpense}
        />
        <ExpenseForm
          onExpenseAdded={onRefresh}
          {refreshKey}
          {editingExpense}
          onCancelEdit={handleCancelEdit}
        />
      </div>

      <div class="dashboard-column">
        <BalanceSummary {balances} />
        <SettlementCard
          {settlements}
          onSettle={handleSettle}
          isSimplified={group.simplify_debts}
          onToggleSimplify={handleToggleSimplify}
        />
      </div>
    </div>
  </div>
{/if}
