// web/src/components/GroupHeader.tsx
import React, { useState } from "react";

interface GroupHeaderProps {
  groupName: string;
  groupId: number;
  onUpdateGroup: (groupId: number, newName: string) => Promise<void>;
  onDeleteGroup: () => void;
}

const GroupHeader: React.FC<GroupHeaderProps> = ({
  groupName,
  groupId,
  onUpdateGroup,
  onDeleteGroup,
}) => {
  const [isEditing, setIsEditing] = useState(false);
  const [editedName, setEditedName] = useState("");

  const startEdit = () => {
    setEditedName(groupName);
    setIsEditing(true);
  };

  const cancelEdit = () => {
    setIsEditing(false);
    setEditedName("");
  };

  const saveEdit = async () => {
    if (!editedName.trim()) return;

    try {
      await onUpdateGroup(groupId, editedName);
      setIsEditing(false);
      setEditedName("");
    } catch {
      setEditedName(groupName);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter") saveEdit();
    if (e.key === "Escape") cancelEdit();
  };

  return (
    <div className="dashboard-group-header">
      {isEditing ? (
        <div className="edit-form-row">
          <input
            type="text"
            className="form-control edit-form-input"
            value={editedName}
            onChange={(e) => setEditedName(e.target.value)}
            onKeyDown={handleKeyDown}
            autoFocus
          />
          <button className="btn btn-sm btn-success" onClick={saveEdit}>
            Save
          </button>
          <button className="btn btn-sm btn-secondary" onClick={cancelEdit}>
            Cancel
          </button>
        </div>
      ) : (
        <div className="flex-between">
          <h3 className="dashboard-group-name">{groupName}</h3>
          <div className="flex-center gap-sm">
            <button
              className="btn btn-sm btn-secondary"
              onClick={startEdit}
              title="Edit group name"
            >
              Edit
            </button>
            <button
              className="btn btn-sm btn-danger"
              onClick={onDeleteGroup}
              title="Delete group"
            >
              Delete
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default GroupHeader;

// web/src/lib/GroupHeader.svelte
<script lang="ts">
  interface Props {
    groupName: string;
    groupId: number;
    onUpdateGroup: (groupId: number, newName: string) => Promise<void>;
    onDeleteGroup: () => void;
  }

  let { groupName, groupId, onUpdateGroup, onDeleteGroup }: Props = $props();

  let isEditing = $state(false);
  let editedName = $state("");

  function startEdit() {
    editedName = groupName;
    isEditing = true;
  }

  function cancelEdit() {
    isEditing = false;
    editedName = "";
  }

  async function saveEdit() {
    if (!editedName.trim()) return;

    try {
      await onUpdateGroup(groupId, editedName);
      isEditing = false;
      editedName = "";
    } catch {
      editedName = groupName;
    }
  }

  function handleKeyDown(e: KeyboardEvent) {
    if (e.key === "Enter") saveEdit();
    if (e.key === "Escape") cancelEdit();
  }
</script>

<div class="dashboard-group-header">
  {#if isEditing}
    <div class="edit-form-row">
      <!-- svelte-ignore a11y_autofocus -->
      <input
        type="text"
        class="form-control edit-form-input"
        bind:value={editedName}
        onkeydown={handleKeyDown}
        autofocus
      />
      <button class="btn btn-sm btn-success" onclick={saveEdit}>Save</button>
      <button class="btn btn-sm btn-secondary" onclick={cancelEdit}>Cancel</button>
    </div>
  {:else}
    <div class="flex-between">
      <h3 class="dashboard-group-name">{groupName}</h3>
      <div class="flex-center gap-sm">
        <button
          class="btn btn-sm btn-secondary"
          onclick={startEdit}
          title="Edit group name"
        >
          Edit
        </button>
        <button
          class="btn btn-sm btn-danger"
          onclick={onDeleteGroup}
          title="Delete group"
        >
          Delete
        </button>
      </div>
    </div>
  {/if}
</div>
