// web/src/components/LoginPage.tsx
import { useState } from "react";
import { useAuth } from "../contexts/AuthContext";
import { useToast } from "../contexts/ToastContext";
import { formatPhoneNumber, isValidPhone } from "../utils/phone";

type Mode = "signin" | "signup";

export default function LoginPage() {
  const { register, login } = useAuth();
  const toast = useToast();
  const [mode, setMode] = useState<Mode>("signin");
  const [phone, setPhone] = useState("");
  const [name, setName] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);

  const validPhone = isValidPhone(phone);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!validPhone) return;
    if (mode === "signup" && !name.trim()) return;

    setIsSubmitting(true);
    try {
      if (mode === "signup") {
        await register(phone.trim(), name.trim());
      } else {
        await login(phone.trim());
      }
    } catch (error) {
      toast.error(
        error instanceof Error
          ? error.message
          : mode === "signup"
            ? "Registration failed. Please try again."
            : "Sign in failed. Please try again.",
      );
    } finally {
      setIsSubmitting(false);
    }
  };

  const switchMode = () => {
    setMode(mode === "signin" ? "signup" : "signin");
    setName("");
  };

  return (
    <div className="welcome-page">
      <div className="welcome-card">
        <h1 className="welcome-title">Splitdumb</h1>
        <p className="welcome-subtitle">
          Split expenses with friends, the simple way.
        </p>
        <form onSubmit={handleSubmit} className="welcome-form">
          <input
            type="tel"
            className="form-control welcome-input"
            placeholder="Phone number (XXX-XXXX-XXXX)"
            value={phone}
            onChange={(e) => setPhone(formatPhoneNumber(e.target.value))}
            autoFocus
            disabled={isSubmitting}
          />
          {mode === "signup" && (
            <input
              type="text"
              className="form-control welcome-input"
              placeholder="Your name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              disabled={isSubmitting}
            />
          )}
          <button
            type="submit"
            className="btn btn-primary welcome-button"
            disabled={
              isSubmitting || !validPhone || (mode === "signup" && !name.trim())
            }
          >
            {isSubmitting
              ? mode === "signup"
                ? "Creating account..."
                : "Signing in..."
              : mode === "signup"
                ? "Sign Up"
                : "Sign In"}
          </button>
        </form>
        <p className="auth-switch">
          {mode === "signin" ? (
            <>
              Don't have an account?{" "}
              <button
                type="button"
                className="link-button"
                onClick={switchMode}
              >
                Sign Up
              </button>
            </>
          ) : (
            <>
              Already have an account?{" "}
              <button
                type="button"
                className="link-button"
                onClick={switchMode}
              >
                Sign In
              </button>
            </>
          )}
        </p>
      </div>
    </div>
  );
}

// web/src/lib/LoginPage.svelte
<script lang="ts">
  import { auth } from "./stores/auth";
  import { toast } from "./stores/toast";
  import { formatPhoneNumber, isValidPhone } from "./utils/phone";

  type Mode = "signin" | "signup";

  let mode = $state<Mode>("signin");
  let phone = $state("");
  let name = $state("");
  let isSubmitting = $state(false);

  let validPhone = $derived(isValidPhone(phone));

  function handlePhoneInput(e: Event) {
    const target = e.target as HTMLInputElement;
    phone = formatPhoneNumber(target.value);
  }

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    if (!validPhone) return;
    if (mode === "signup" && !name.trim()) return;

    isSubmitting = true;
    try {
      if (mode === "signup") {
        await auth.register(phone.trim(), name.trim());
      } else {
        await auth.login(phone.trim());
      }
    } catch (error) {
      toast.error(
        error instanceof Error
          ? error.message
          : mode === "signup"
            ? "Registration failed. Please try again."
            : "Sign in failed. Please try again."
      );
    } finally {
      isSubmitting = false;
    }
  }

  function switchMode() {
    mode = mode === "signin" ? "signup" : "signin";
    name = "";
  }
</script>

<div class="welcome-page">
  <div class="welcome-card">
    <h1 class="welcome-title">Splitdumb</h1>
    <p class="welcome-subtitle">Split expenses with friends, the simple way.</p>
    <form onsubmit={handleSubmit} class="welcome-form">
      <!-- svelte-ignore a11y_autofocus -->
      <input
        type="tel"
        class="form-control welcome-input"
        placeholder="Phone number (XXX-XXX-XXXX)"
        value={phone}
        oninput={handlePhoneInput}
        autofocus
        disabled={isSubmitting}
      />
      {#if mode === "signup"}
        <input
          type="text"
          class="form-control welcome-input"
          placeholder="Your name"
          bind:value={name}
          disabled={isSubmitting}
        />
      {/if}
      <button
        type="submit"
        class="btn btn-primary welcome-button"
        disabled={isSubmitting || !validPhone || (mode === "signup" && !name.trim())}
      >
        {#if isSubmitting}
          {mode === "signup" ? "Creating account..." : "Signing in..."}
        {:else}
          {mode === "signup" ? "Sign Up" : "Sign In"}
        {/if}
      </button>
    </form>
    <p class="auth-switch">
      {#if mode === "signin"}
        Don't have an account?
        <button type="button" class="link-button" onclick={switchMode}>
          Sign Up
        </button>
      {:else}
        Already have an account?
        <button type="button" class="link-button" onclick={switchMode}>
          Sign In
        </button>
      {/if}
    </p>
  </div>
</div>
