// web/src/lib/BalanceSummary.svelte
<script lang="ts">
  interface Props {
    balances: Record<string, number>;
  }

  let { balances }: Props = $props();

  let sortedBalances = $derived(
    Object.entries(balances).sort(([a], [b]) => a.localeCompare(b))
  );
</script>

<div class="card dashboard-card mt-3">
  <div class="card-body">
    <h5 class="card-title">Balance Summary</h5>
    <div class="list-group">
      {#each sortedBalances as [user, balance] (user)}
        <div class="balance-item list-group-item">
          <span class="balance-name">{user}</span>
          <span class="balance-amount {balance >= 0 ? 'text-success' : 'text-danger'}">
            {balance >= 0 ? "+" : ""}${balance.toFixed(2)}
          </span>
        </div>
      {/each}
    </div>
  </div>
</div>

// web/src/components/BalanceSummary.tsx
import React, { memo } from "react";

interface BalanceSummaryProps {
  balances: Record<string, number>;
}

const BalanceSummary: React.FC<BalanceSummaryProps> = memo(({ balances }) => {
  const sortedBalances = Object.entries(balances).sort(([a], [b]) =>
    a.localeCompare(b),
  );

  return (
    <div className="card dashboard-card mt-3">
      <div className="card-body">
        <h5 className="card-title">Balance Summary</h5>
        <div className="list-group">
          {sortedBalances.map(([user, balance]) => (
            <div key={user} className="balance-item list-group-item">
              <span className="balance-name">{user}</span>
              <span
                className={`balance-amount ${balance >= 0 ? "text-success" : "text-danger"}`}
              >
                {balance >= 0 ? "+" : ""}${balance.toFixed(2)}
              </span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
});

BalanceSummary.displayName = "BalanceSummary";

export default BalanceSummary;
